#Function that allows preprocessing files through pipes
# 
#Args:
# 
#pathFiles: (character) path of files that will be preprocessed
#pipe: (TypePipe) the class that inherits from TypePipe and that implements the 
#                 flow of pipes. By default the super class has implemented a 
#                 default sequence of pipes
#pathKeys: (character) configuration file path
#pathOutPut: (character) path of the file generated from the built data frame 
# 
# Returns:
# dataFrame: (data.frame) The generated data.frame is returned when the instances 
#                         are preprocessed
proccess_files = function(pathFiles, 
                          pipe, 
                          pathKeys = "content-preprocessorinr/config/configurations.ini", 
                          pathOutPut = "output.RData") {
  
  if (!"character" %in% class(pathFiles)) {
    stop("[proccess_files][Error] 
            Checking the type of the variable: pathFiles ", 
              class(pathFiles))
  } 
  
  if (!"TypePipe" %in% class(pipe)) {
    stop("[proccess_files][Error] 
            Checking the type of the variable: pipe ", 
              class(pipe))
  } 
  
  if (!"character" %in% class(pathKeys)) {
    stop("[proccess_files][Error] 
            Checking the type of the variable: pathKeys ", 
              class(pathKeys))
  }  
  
  if (!"ini" %in% file_ext(pathKeys)) {
    stop("[proccess_files][Error]
            Checking the extension of the file: pathKeys ",
              file_ext(pathKeys))
  }
  
  if (!"character" %in% class(pathOutPut)) {
    stop("[proccess_files][Error] 
            Checking the type of the variable: pathOutPut ", 
              class(pathOutPut))
  }  
  
  if (!file_ext(pathOutPut) %in% "csv" & !file_ext(pathOutPut) %in% "RData") {
    stop("[proccess_files][Error] 
            Checking the extension of the variable: pathOutPut",
              file_ext(pathKeys))
  }
  
  synsetDictionary <<- SynsetDictionary$new()
  #Initialize the object that handles the different types of connections with babelfy and babelnet
  babelUtils <<- BabelUtils$new(pathKeys)
  #Array of files to preprocess
  Files <- list.files(path = pathFiles, recursive = TRUE, full.names = TRUE, all.files = TRUE)
  
  #Initialize the object that handles the different types of connections with youtube and twitter
  connections <<- Connections$new(pathKeys)
  #Initialize the object that manages the loading of the resource files, such as 
  #abbreviation, slang, stopword, etc.
  resourceHandle <<- ResourceHandler$new()
  #Variable in which the data.frame generated by the pipes will be saved
  dataFrameAll <<- data.frame()
  
  #Create the list of instances, which will contain the date, source, path, data 
  #and a list of properties of the file that is in the indicated path
  InstancesList <- sapply(Files, InstanceFactory$new()$createInstance)
  cat("[proccess_files][Info] ", "Has been created: ", length(InstancesList)," instances.\n")
  listInstances <- sapply(InstancesList, pipe$pipeAll)
  
  if (file_ext(pathOutPut) %in% "csv") {
    write.table(x = dataFrameAll, 
                file = pathOutPut, 
                sep = ";", quote = T,
                col.names = TRUE, row.names = FALSE,
                qmethod = c("double"),
                fileEncoding = "UTF-8")
  } else {
    
    if (file_ext(pathOutPut) %in% "RData") {
      saveRDS(get("dataFrame"), file = pathOutPut)
    } else {
      stop("[proccess_files][Error] 
              Checking the extension of the variable: pathOutPut",
                file_ext(pathKeys))
    }
  }
  
  return(listInstances)
}